# -*- coding: utf-8 -*-
"""Monoalphabatic cipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-L50uNaC7UWbbkgk1uQ_MEFz3tEfQgg9
"""

Key = {
      "a":"z", 'b':'y', 'c':'x', 'd':'w', 'e':'v', 'f':'u', 'g':'t', 'h':'s', 'i':'r', 
       'j':'q', 'k':'p', 'l':'o', 'm':'n', 'n':'m', 'o':'l', 'p':'k', 'q':'j', 'r':'i', 
       's':'h', 't':'g','u':'f', 'v':'e', 'w':'d', 'x':'c', 'y':'b', 'z':'a', " ":" ", ".":"."
  }
key_list = list(Key.keys())
val_list = list(Key.values())
s=''
def encrypt(word):
  word=word.lower()
  ls=[val_list.index(i) for i in word]
  ls2=[key_list[j] for j in ls]
  x=s.join(ls2)
  return (s.join(ls2))

def decrypt(word):
  word=word.lower()
  ls=[key_list.index(i) for i in word]
  ls2=[val_list[j] for j in ls]
  return (s.join(ls2))


word=input("Enter the plain text: ")
x=encrypt(word)
print("Cipher text encrypted: "+ x)
print("Decrypt text: "+decrypt(x))

