# -*- coding: utf-8 -*-
"""date.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ule31aNs8dAJ4PHpgrsE0WefraXHSe76
"""

# Python program to display current date and time

import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))

